### ISSUE TITLE
About the calculation of E_gcdft

### ISSUE THREAD

**Issue by RedStar-Iron** [zishengz/echo#1]
![image](https://user-images.githubusercontent.com/49940294/185776164-45ade75a-2b50-44f1-9a70-cd708e3f0311.png)
As shown in the picture, E_gcdft = E_dft + nelect_net*(fermi_shift+work_function)
but work_function = -e_fermi - fermi_shift, so combine these two equations we can find E_gcdft is unrelated to the fermi_shift. Is that right? 
To be honest, I feel confused about the method to calculate the E_gcdft even though I read the paper "First principles reaction modeling of the electrochemical interface: Consideration and calculation of a tunable surface potential from atomic and electronic structure". Could you please tell me which paper or tutorial I shoud read? 

Thanks

**Comment by zishengz** [comment]
I suggest reading the original publication of VASPsol by Hennig group: J. Chem. Phys. 151, 234101 (2019)
Regarding the elimination of fermi shift in the free energy, it is due to a correction term. Note that it is technical, not physical.
![image](https://user-images.githubusercontent.com/16268989/198377609-f316b5de-9e75-4a9d-88e3-6d031af13bb5.png)

**Comment by RedStar-Iron** [comment]
Thanks a lot!!!
I will read that paper.
